# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow runs Parasoft C/C++test Standard to analyze code
# and display results with GitHub code scanning alerts.
#
# This workflow is pre-configured for Make-based C/C++ projects.
# Uncomment sections marked with '[CMAKE]' for CMake-based C/C++ projects.
#
# Parasoft C/C++test uses a comprehensive set of analysis techniques,
# including pattern-based static analysis, dataflow analysis, metrics,
# code coverage, unit testing, and more, to help you verify code quality
# and ensure compliance with industry standards, such as MISRA, AUTOSAR, and CERT.
#
# See https://github.com/marketplace/actions/run-parasoft-c-c-test for more information.


name: Parasoft C/C++test Code Analysis

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ $default-branch ]
  schedule:
    - cron: $cron-weekly

jobs:
  run-cpptest:
    name: Analyze project with C/C++test

    # Code analysis with Parasoft C/C++test requires a self-hosted runner
    # where Parasoft C/C++test is installed and properly licensed.
    runs-on: self-hosted

    steps:

    # Checks out your repository.
    - name: Checkout code
      uses: actions/checkout@v2
    
    # [MAKE]
    # Builds your Make project using 'cpptesttrace' to collect input data for code analysis.
    # Be sure 'cpptesttrace' is available on $PATH.
    - name: Build project
      run: cpptesttrace make clean all

    # [CMAKE]
    # Configures your CMake project. Be sure the compile_commands.json file is created.
    # - name: Configure project
    #   run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -S . -B build

    # [CMAKE]
    # Builds your CMake project. This step is optional, as it is not required for code analysis.
    # - name: Build project (optional)
    #   run: cmake --build build

    # Runs code analysis with C/C++test Standard.
    # See https://github.com/marketplace/actions/run-parasoft-c-c-test for more information.
    - name: Run C/C++test
      # Use the 'run-cpptest-action' GitHub action.
      uses: parasoft/run-cpptest-action@104f1c9cf6dbfd4b22e248a41d2e5a1e25e68b9e
      with:
        # Compiler configuration - ensure you specify the configuration that matches your compiler.
        compilerConfig: 'gcc_9-64'        
        
        # Test configuration.
        testConfig: 'builtin://Recommended Rules'
        
        # Input scope for analysis.
        # [MAKE] Use 'cpptestscan.bdf' file generated by 'cpptesttrace' utility:
        input: cpptestscan.bdf
        # [CMAKE] Use 'build/compile_commands.json' file generated by CMake: 
        # input: build/compile_commands.json

        # Uncomment if you are using C/C++test 2020.2 to generate a SARIF report:
        # reportFormat: xml,html,custom
        # additionalParams: '-property report.custom.extension=sarif -property report.custom.xsl.file=${PARASOFT_SARIF_XSL}'

    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports/report.sarif
    
    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      uses: actions/upload-artifact@v2
      with:
        name: Static analysis reports
        path: reports/*.*
